CLIENT_EVENTS = {
    "START_CONNECTION": 1,
    "FINISH_CONNECTION": 2,
    "START_SESSION": 100,
    "FINISH_SESSION": 102,
    "TASK_REQUEST": 200,
    "SAY_HELLO": 300,
    "CHAT_TEXT_QUERY": 501,
    "CLIENT_INTERRUPT": 515,
}

SERVER_EVENTS = {
    "CONNECTION_STARTED": 50,
    "CONNECTION_FAILED": 51,
    "CONNECTION_FINISHED": 52,
    "SESSION_STARTED": 150,
    "SESSION_FINISHED": 152,
    "SESSION_FAILED": 153,
    "USAGE_RESPONSE": 154,
    "TTS_SENTENCE_START": 350,
    "TTS_SENTENCE_END": 351,
    "TTS_RESPONSE": 352,
    "TTS_ENDED": 359,
    "ASR_RESPONSE": 451,
    "ASR_ENDED": 459,
    "CHAT_RESPONSE": 550,
    "CHAT_ENDED": 559,
}
